spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: root
    password: 123456
    driver-class-name: org.gjt.mm.mysql.Driver

  #配置Redis
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 3
    # redis服务器地址：默认为localhost
    host: localhost
    # redis端口：默认为6379
    port: 6379
    # redis访问密码：默认为空
    password:
    # redis连接超时时间：单位为毫秒
    timeout: 0
    # redis连接池配置
    pool:
      # 最大可用连接数：默认为8，负数表示无限
      max-active: 8
      # 最大空闲连接数：默认为8，负数表示无限
      max-idle: 8
      # 最小空余连接数：默认为0，该值只有正数才有作用
      min-idle: 0
      # 从连接池中获取连接最大等待时间：默认为-1，单位为毫秒，负数表示无限
      max-wait: -1

#服务器配置
server:
  port: 8081

#mybatis配置
mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.vechace.weblearning.Dao.domain
  # 配置mapper.xml文件所在位置
  mapper-locations:
    - mappers/ProductMapper.xml

# 日志级别配置
logging:
  level:
    com.vechace.weblearning: DEBUG

---
# 另起一个测试配置数据源
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: 123456
    driver-class-name: org.h2.Driver
    # 配置测试数据源SQL
    schema: classpath:schema.sql
    data: classpath:data.sql


